//Los types los manejo con mayúsculas por que según es buena práctica

export const types = {
    GET_POKEMON: 'GET_POKEMON',
    POKEMON_GET_SUCESS: 'POKEMON_GET_SUCESS',
    POKEMON_GET_ERROR: 'POKEMON_GET_ERROR',

    GET_POKEMON_SEARCH:'GET_POKEMON_SEARCH',
    POKEMON_SEARCH_GET_SUCESS:'GET_POKEMON_SEARCH_SUCESS',
    POKEMON_SEARCH_GET_ERROR: 'POKEMON_GET_ERROR',

    OPEN_MODAL_POKEMON:'OPEN_MODAL_POKEMON',
    CLOSE_MODAL_POKEMON: 'CLOSE_MODAL_POKEMON',

    GET_POKEMON_ITEM:'GET_POKEMON_ITEM',
    POKEMON_ITEM_GET_SUCESS:'POKEMON_ITEM_GET_SUCESS',
    POKEMON_ITEM_GET_ERROR: 'POKEMON_ITEM_GET_ERROR',
}